Adds load_balancer resource template
Azure/caf-terraform-landingzones pull request #364
Opened 2022-05-02 18:45 UTC by tschwarz01

# [Issue-id](https://github.com/Azure/caf-terraform-landingzones/issues/ISSUE-ID-GOES-HERE)

## PR Checklist

---

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [X ] My code follows the code style of this project.
- [ ] I ran lint checks locally prior to submission.
- [X ] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

Adds load_balancers to the available resource templates

## Does this introduce a breaking change

- [ ] YES
- [X ] NO

## Testing

      load_balancers:
        lb-vmss:
          name: lb-vmss
          sku: basic
          resource_group_key: integration
          backend_address_pool_name: vmss1
          frontend_ip_configurations:
            config1:
              name: config1
              public_ip_address_key: lb_pip1
          probes:
            probe1:
              resource_group_key: integration
              load_balancer_key: lb-vmss
              probe_name: rdp
              port: 3389
          lb_rules:
            rule1:
              resource_group_key: integration
              load_balancer_key: lb-vmss
              lb_rule_name: rule1
              protocol: tcp
              probe_id_key: probe1
              frontend_port: 3389
              backend_port: 3389
              frontend_ip_configuration_name: config1

2022-05-04 14:23 UTC, LaurentLesle requested changes

2022-05-04 14:23 UTC, LaurentLesle commented on templates/resources/load_balancers.tfvars.j2
> +        zones     = "{{ config.zones }}"
zones is a list. So you need to adjust the code to get it back to a terraform HCL list

```
{% if disk_value.zones is defined %}
          zones = {{ disk_value.zones | map('string') | replace('None','[]') | replace('\'','\"') }}
{% endif %}
```

2022-05-04 14:23 UTC, LaurentLesle commented on templates/resources/load_balancers.tfvars.j2
> +      tags                = {{ lbs.tags }}
Same add the for loop

2022-05-04 15:20 UTC, tschwarz01 commented on templates/resources/load_balancers.tfvars.j2
> +      tags                = {{ lbs.tags }}
Complete

2022-05-25 11:52 UTC, LaurentLesle commented
load_balancers is replaced by lb

2022-05-25 12:19 UTC, LaurentLesle approved these changes

2022-05-25 12:25 UTC, merged